app_name = "shetue_custom"
app_title = "Shetue MultiBiz Custom App"
app_publisher = "Sohel Huq"
app_description = "Customizations for Shetue MultiBiz ERPNext"
app_version = "0.0.1"
# app_email = "your_email@example.com"
# app_license = "MIT"
